name: pasteall_mobile
description: PasteAll移动端应用 - 跨平台近距离设备复制粘贴工具
publish_to: 'none' 

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  flutter_rust_bridge: ^1.78.0
  ffi: ^2.0.2
  permission_handler: ^10.4.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.3.0
  flutter_blue_plus: ^1.14.7
  nearby_connections: ^3.3.0
  clipboard: ^0.1.3
  file_picker: ^5.3.2
  path: ^1.8.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  ffigen: ^8.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
